// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: telemetry/v1/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operational autopilot flight modes (compatible with PX4 and ROS2 autonomy).
type FlightMode int32

const (
	FlightMode_FLIGHT_MODE_UNSPECIFIED   FlightMode = 0
	FlightMode_FLIGHT_MODE_MANUAL        FlightMode = 1
	FlightMode_FLIGHT_MODE_ALTITUDE_HOLD FlightMode = 2
	FlightMode_FLIGHT_MODE_POSITION_HOLD FlightMode = 3
	FlightMode_FLIGHT_MODE_AUTO_MISSION  FlightMode = 4
	FlightMode_FLIGHT_MODE_AUTO_RTL      FlightMode = 5 // Return To Launch
	FlightMode_FLIGHT_MODE_AUTO_LAND     FlightMode = 6
	FlightMode_FLIGHT_MODE_OFFBOARD      FlightMode = 7 // Companion computer setpoint control
)

// Enum value maps for FlightMode.
var (
	FlightMode_name = map[int32]string{
		0: "FLIGHT_MODE_UNSPECIFIED",
		1: "FLIGHT_MODE_MANUAL",
		2: "FLIGHT_MODE_ALTITUDE_HOLD",
		3: "FLIGHT_MODE_POSITION_HOLD",
		4: "FLIGHT_MODE_AUTO_MISSION",
		5: "FLIGHT_MODE_AUTO_RTL",
		6: "FLIGHT_MODE_AUTO_LAND",
		7: "FLIGHT_MODE_OFFBOARD",
	}
	FlightMode_value = map[string]int32{
		"FLIGHT_MODE_UNSPECIFIED":   0,
		"FLIGHT_MODE_MANUAL":        1,
		"FLIGHT_MODE_ALTITUDE_HOLD": 2,
		"FLIGHT_MODE_POSITION_HOLD": 3,
		"FLIGHT_MODE_AUTO_MISSION":  4,
		"FLIGHT_MODE_AUTO_RTL":      5,
		"FLIGHT_MODE_AUTO_LAND":     6,
		"FLIGHT_MODE_OFFBOARD":      7,
	}
)

func (x FlightMode) Enum() *FlightMode {
	p := new(FlightMode)
	*p = x
	return p
}

func (x FlightMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlightMode) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (FlightMode) Type() protoreflect.EnumType {
	return &file_telemetry_v1_telemetry_proto_enumTypes[0]
}

func (x FlightMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlightMode.Descriptor instead.
func (FlightMode) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

// Overall UAV hardware and subsystem health state.
type SystemStatus int32

const (
	SystemStatus_SYSTEM_STATUS_UNSPECIFIED SystemStatus = 0
	SystemStatus_SYSTEM_STATUS_BOOTING     SystemStatus = 1
	SystemStatus_SYSTEM_STATUS_CALIBRATING SystemStatus = 2
	SystemStatus_SYSTEM_STATUS_STANDBY     SystemStatus = 3
	SystemStatus_SYSTEM_STATUS_ACTIVE      SystemStatus = 4
	SystemStatus_SYSTEM_STATUS_CRITICAL    SystemStatus = 5
	SystemStatus_SYSTEM_STATUS_EMERGENCY   SystemStatus = 6
)

// Enum value maps for SystemStatus.
var (
	SystemStatus_name = map[int32]string{
		0: "SYSTEM_STATUS_UNSPECIFIED",
		1: "SYSTEM_STATUS_BOOTING",
		2: "SYSTEM_STATUS_CALIBRATING",
		3: "SYSTEM_STATUS_STANDBY",
		4: "SYSTEM_STATUS_ACTIVE",
		5: "SYSTEM_STATUS_CRITICAL",
		6: "SYSTEM_STATUS_EMERGENCY",
	}
	SystemStatus_value = map[string]int32{
		"SYSTEM_STATUS_UNSPECIFIED": 0,
		"SYSTEM_STATUS_BOOTING":     1,
		"SYSTEM_STATUS_CALIBRATING": 2,
		"SYSTEM_STATUS_STANDBY":     3,
		"SYSTEM_STATUS_ACTIVE":      4,
		"SYSTEM_STATUS_CRITICAL":    5,
		"SYSTEM_STATUS_EMERGENCY":   6,
	}
)

func (x SystemStatus) Enum() *SystemStatus {
	p := new(SystemStatus)
	*p = x
	return p
}

func (x SystemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_v1_telemetry_proto_enumTypes[1].Descriptor()
}

func (SystemStatus) Type() protoreflect.EnumType {
	return &file_telemetry_v1_telemetry_proto_enumTypes[1]
}

func (x SystemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemStatus.Descriptor instead.
func (SystemStatus) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

// 3D Cartesian vector in standard SI units (meters or meters per second).
type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

// Orientation quaternion following Hamilton convention (w + xi + yj + zk).
type Quaternion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             float64                `protobuf:"fixed64,1,opt,name=w,proto3" json:"w,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,4,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quaternion) Reset() {
	*x = Quaternion{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quaternion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quaternion) ProtoMessage() {}

func (x *Quaternion) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quaternion.ProtoReflect.Descriptor instead.
func (*Quaternion) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Quaternion) GetW() float64 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Quaternion) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Quaternion) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Quaternion) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

// Attitude orientation represented in Tait-Bryan Euler angles (radians).
type EulerAngles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roll          float64                `protobuf:"fixed64,1,opt,name=roll,proto3" json:"roll,omitempty"`   // Rotation around X axis (radians, [-pi, pi])
	Pitch         float64                `protobuf:"fixed64,2,opt,name=pitch,proto3" json:"pitch,omitempty"` // Rotation around Y axis (radians, [-pi/2, pi/2])
	Yaw           float64                `protobuf:"fixed64,3,opt,name=yaw,proto3" json:"yaw,omitempty"`     // Rotation around Z axis (radians, [-pi, pi])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EulerAngles) Reset() {
	*x = EulerAngles{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EulerAngles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EulerAngles) ProtoMessage() {}

func (x *EulerAngles) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EulerAngles.ProtoReflect.Descriptor instead.
func (*EulerAngles) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *EulerAngles) GetRoll() float64 {
	if x != nil {
		return x.Roll
	}
	return 0
}

func (x *EulerAngles) GetPitch() float64 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *EulerAngles) GetYaw() float64 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

// Battery power and health metrics.
type BatteryState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoltageV      float32                `protobuf:"fixed32,1,opt,name=voltage_v,json=voltageV,proto3" json:"voltage_v,omitempty"`             // Terminal voltage in Volts (e.g. 15.2V for 4S LiPo)
	CurrentA      float32                `protobuf:"fixed32,2,opt,name=current_a,json=currentA,proto3" json:"current_a,omitempty"`             // Instantaneous current draw in Amperes
	Percentage    float32                `protobuf:"fixed32,3,opt,name=percentage,proto3" json:"percentage,omitempty"`                         // Remaining capacity ratio [0.0 - 1.0]
	TemperatureC  float32                `protobuf:"fixed32,4,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"` // Battery cell temperature in Celsius
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatteryState) Reset() {
	*x = BatteryState{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatteryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryState) ProtoMessage() {}

func (x *BatteryState) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryState.ProtoReflect.Descriptor instead.
func (*BatteryState) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *BatteryState) GetVoltageV() float32 {
	if x != nil {
		return x.VoltageV
	}
	return 0
}

func (x *BatteryState) GetCurrentA() float32 {
	if x != nil {
		return x.CurrentA
	}
	return 0
}

func (x *BatteryState) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *BatteryState) GetTemperatureC() float32 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

// UAV Telemetry record broadcasted at high frequencies (up to 100 Hz).
type TelemetryRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- Header & Synchronization ---
	DeviceId       string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                    // Unique UAV identifier (e.g. "uav-alpha-01")
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // Monotonically increasing datagram counter
	TimestampNs    int64  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`          // Unix epoch timestamp in nanoseconds captured at edge
	// --- Kinematics & Spatial State ---
	Position        *Vector3     `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`                                      // 3D position (X=North, Y=East, Z=Down / ENU in meters)
	Orientation     *Quaternion  `protobuf:"bytes,5,opt,name=orientation,proto3" json:"orientation,omitempty"`                                // Attitude quaternion
	EulerAngles     *EulerAngles `protobuf:"bytes,6,opt,name=euler_angles,json=eulerAngles,proto3" json:"euler_angles,omitempty"`             // Attitude in Euler angles (radians)
	LinearVelocity  *Vector3     `protobuf:"bytes,7,opt,name=linear_velocity,json=linearVelocity,proto3" json:"linear_velocity,omitempty"`    // Linear velocity vector (m/s)
	AngularVelocity *Vector3     `protobuf:"bytes,8,opt,name=angular_velocity,json=angularVelocity,proto3" json:"angular_velocity,omitempty"` // Angular velocity / body rates (rad/s)
	// --- Autopilot & Power State ---
	Armed         bool          `protobuf:"varint,9,opt,name=armed,proto3" json:"armed,omitempty"`                                                                   // True when propulsion motors are active
	FlightMode    FlightMode    `protobuf:"varint,10,opt,name=flight_mode,json=flightMode,proto3,enum=telemetry.v1.FlightMode" json:"flight_mode,omitempty"`         // Current flight mode
	SystemStatus  SystemStatus  `protobuf:"varint,11,opt,name=system_status,json=systemStatus,proto3,enum=telemetry.v1.SystemStatus" json:"system_status,omitempty"` // Overall health/system status
	Battery       *BatteryState `protobuf:"bytes,12,opt,name=battery,proto3" json:"battery,omitempty"`                                                               // Battery telemetry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRecord) Reset() {
	*x = TelemetryRecord{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRecord) ProtoMessage() {}

func (x *TelemetryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRecord.ProtoReflect.Descriptor instead.
func (*TelemetryRecord) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *TelemetryRecord) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryRecord) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *TelemetryRecord) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *TelemetryRecord) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *TelemetryRecord) GetOrientation() *Quaternion {
	if x != nil {
		return x.Orientation
	}
	return nil
}

func (x *TelemetryRecord) GetEulerAngles() *EulerAngles {
	if x != nil {
		return x.EulerAngles
	}
	return nil
}

func (x *TelemetryRecord) GetLinearVelocity() *Vector3 {
	if x != nil {
		return x.LinearVelocity
	}
	return nil
}

func (x *TelemetryRecord) GetAngularVelocity() *Vector3 {
	if x != nil {
		return x.AngularVelocity
	}
	return nil
}

func (x *TelemetryRecord) GetArmed() bool {
	if x != nil {
		return x.Armed
	}
	return false
}

func (x *TelemetryRecord) GetFlightMode() FlightMode {
	if x != nil {
		return x.FlightMode
	}
	return FlightMode_FLIGHT_MODE_UNSPECIFIED
}

func (x *TelemetryRecord) GetSystemStatus() SystemStatus {
	if x != nil {
		return x.SystemStatus
	}
	return SystemStatus_SYSTEM_STATUS_UNSPECIFIED
}

func (x *TelemetryRecord) GetBattery() *BatteryState {
	if x != nil {
		return x.Battery
	}
	return nil
}

var File_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1ctelemetry/v1/telemetry.proto\x12\ftelemetry.v1\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"D\n" +
	"\n" +
	"Quaternion\x12\f\n" +
	"\x01w\x18\x01 \x01(\x01R\x01w\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x01R\x01z\"I\n" +
	"\vEulerAngles\x12\x12\n" +
	"\x04roll\x18\x01 \x01(\x01R\x04roll\x12\x14\n" +
	"\x05pitch\x18\x02 \x01(\x01R\x05pitch\x12\x10\n" +
	"\x03yaw\x18\x03 \x01(\x01R\x03yaw\"\x8d\x01\n" +
	"\fBatteryState\x12\x1b\n" +
	"\tvoltage_v\x18\x01 \x01(\x02R\bvoltageV\x12\x1b\n" +
	"\tcurrent_a\x18\x02 \x01(\x02R\bcurrentA\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x02R\n" +
	"percentage\x12#\n" +
	"\rtemperature_c\x18\x04 \x01(\x02R\ftemperatureC\"\xf1\x04\n" +
	"\x0fTelemetryRecord\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\x121\n" +
	"\bposition\x18\x04 \x01(\v2\x15.telemetry.v1.Vector3R\bposition\x12:\n" +
	"\vorientation\x18\x05 \x01(\v2\x18.telemetry.v1.QuaternionR\vorientation\x12<\n" +
	"\feuler_angles\x18\x06 \x01(\v2\x19.telemetry.v1.EulerAnglesR\veulerAngles\x12>\n" +
	"\x0flinear_velocity\x18\a \x01(\v2\x15.telemetry.v1.Vector3R\x0elinearVelocity\x12@\n" +
	"\x10angular_velocity\x18\b \x01(\v2\x15.telemetry.v1.Vector3R\x0fangularVelocity\x12\x14\n" +
	"\x05armed\x18\t \x01(\bR\x05armed\x129\n" +
	"\vflight_mode\x18\n" +
	" \x01(\x0e2\x18.telemetry.v1.FlightModeR\n" +
	"flightMode\x12?\n" +
	"\rsystem_status\x18\v \x01(\x0e2\x1a.telemetry.v1.SystemStatusR\fsystemStatus\x124\n" +
	"\abattery\x18\f \x01(\v2\x1a.telemetry.v1.BatteryStateR\abattery*\xec\x01\n" +
	"\n" +
	"FlightMode\x12\x1b\n" +
	"\x17FLIGHT_MODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FLIGHT_MODE_MANUAL\x10\x01\x12\x1d\n" +
	"\x19FLIGHT_MODE_ALTITUDE_HOLD\x10\x02\x12\x1d\n" +
	"\x19FLIGHT_MODE_POSITION_HOLD\x10\x03\x12\x1c\n" +
	"\x18FLIGHT_MODE_AUTO_MISSION\x10\x04\x12\x18\n" +
	"\x14FLIGHT_MODE_AUTO_RTL\x10\x05\x12\x19\n" +
	"\x15FLIGHT_MODE_AUTO_LAND\x10\x06\x12\x18\n" +
	"\x14FLIGHT_MODE_OFFBOARD\x10\a*\xd5\x01\n" +
	"\fSystemStatus\x12\x1d\n" +
	"\x19SYSTEM_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SYSTEM_STATUS_BOOTING\x10\x01\x12\x1d\n" +
	"\x19SYSTEM_STATUS_CALIBRATING\x10\x02\x12\x19\n" +
	"\x15SYSTEM_STATUS_STANDBY\x10\x03\x12\x18\n" +
	"\x14SYSTEM_STATUS_ACTIVE\x10\x04\x12\x1a\n" +
	"\x16SYSTEM_STATUS_CRITICAL\x10\x05\x12\x1b\n" +
	"\x17SYSTEM_STATUS_EMERGENCY\x10\x06B:Z8github.com/Manex142/uav-lab/pkg/telemetry/v1;telemetryv1b\x06proto3"

var (
	file_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_telemetry_v1_telemetry_proto_rawDescData
}

var file_telemetry_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_telemetry_v1_telemetry_proto_goTypes = []any{
	(FlightMode)(0),         // 0: telemetry.v1.FlightMode
	(SystemStatus)(0),       // 1: telemetry.v1.SystemStatus
	(*Vector3)(nil),         // 2: telemetry.v1.Vector3
	(*Quaternion)(nil),      // 3: telemetry.v1.Quaternion
	(*EulerAngles)(nil),     // 4: telemetry.v1.EulerAngles
	(*BatteryState)(nil),    // 5: telemetry.v1.BatteryState
	(*TelemetryRecord)(nil), // 6: telemetry.v1.TelemetryRecord
}
var file_telemetry_v1_telemetry_proto_depIdxs = []int32{
	2, // 0: telemetry.v1.TelemetryRecord.position:type_name -> telemetry.v1.Vector3
	3, // 1: telemetry.v1.TelemetryRecord.orientation:type_name -> telemetry.v1.Quaternion
	4, // 2: telemetry.v1.TelemetryRecord.euler_angles:type_name -> telemetry.v1.EulerAngles
	2, // 3: telemetry.v1.TelemetryRecord.linear_velocity:type_name -> telemetry.v1.Vector3
	2, // 4: telemetry.v1.TelemetryRecord.angular_velocity:type_name -> telemetry.v1.Vector3
	0, // 5: telemetry.v1.TelemetryRecord.flight_mode:type_name -> telemetry.v1.FlightMode
	1, // 6: telemetry.v1.TelemetryRecord.system_status:type_name -> telemetry.v1.SystemStatus
	5, // 7: telemetry.v1.TelemetryRecord.battery:type_name -> telemetry.v1.BatteryState
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_telemetry_v1_telemetry_proto_init() }
func file_telemetry_v1_telemetry_proto_init() {
	if File_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_telemetry_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_v1_telemetry_proto = out.File
	file_telemetry_v1_telemetry_proto_goTypes = nil
	file_telemetry_v1_telemetry_proto_depIdxs = nil
}
