name: uav-lab

services:
  ros2-jazzy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        USERNAME: manex
        USER_UID: 1000
        USER_GID: 1000
    image: uav-lab:jazzy
    container_name: uav_ros2_jazzy
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/workspace:rw
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: uav_timescaledb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=uav_telemetry
      - POSTGRES_USER=uav_admin
      - POSTGRES_PASSWORD=uav_password
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uav_admin -d uav_telemetry"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  timescale_data:
